name = "eclipse-ytmusic"
main = "index.js"
compatibility_date = "2025-01-01"

[vars]
ADDON_VERSION = "3.1.0"

# Optional: Add a custom domain route below
# [[routes]]
# pattern = "ytmusic.yourdomain.com"
# zone_name = "yourdomain.com"
